export const FETCH_SHOW_PAGE_DATA = 'FETCH_SHOW_PAGE_DATA';
export const FETCH_SHOW_PAGE_DATA_SUCCESS = 'FETCH_SHOW_PAGE_DATA_SUCCESS';
export const FETCH_SHOW_PAGE_DATA_FAILED = 'FETCH_SHOW_PAGE_DATA_FAILED';
