export const FETCH_OTTTEXT_PAGE_DATA = 'FETCH_OTTTEXT_PAGE_DATA';
export const FETCH_OTTTEXT_PAGE_DATA_SUCCESS = 'FETCH_OTTTEXT_PAGE_DATA_SUCCESS';
export const FETCH_OTTTEXT_PAGE_DATA_FAILED = 'FETCH_OTTTEXT_PAGE_DATA_FAILED';
