export const FETCH_STATION_AUTO_SELECTION_DATA = 'FETCH_STATION_AUTO_SELECTION_DATA';
export const FETCH_STATION_AUTO_SELECTION_DATA_SUCCEEDED =
  'FETCH_STATION_AUTO_SELECTION_DATA_SUCCEEDED';
export const FETCH_STATION_AUTO_SELECTION_DATA_FAILED = 'FETCH_STATION_AUTO_SELECTION_DATA_FAILED';

export const FETCH_OTTPAGE_DATA = 'FETCH_OTTPAGE_DATA';
export const FETCH_OTTPAGE_DATA_SUCCESS = 'FETCH_OTTPAGE_DATA_SUCCESS';
export const FETCH_OTTPAGE_DATA_FAILED = 'FETCH_OTTPAGE_DATA_FAILED';
