export const FETCH_CITY_SELECTION_DATA = 'FETCH_CITY_SELECTION_DATA';
export const FETCH_CITY_SELECTION_DATA_SUCCEEDED = 'FETCH_CITY_SELECTION_DATA_SUCCEEDED';
export const FETCH_CITY_SELECTION_DATA_FAILED = 'FETCH_CITY_SELECTION_DATA_FAILED';
