export const FETCH_OTTEPISODE_PAGE_DATA = 'FETCH_OTTEPISODE_PAGE_DATA';
export const FETCH_OTTEPISODE_PAGE_DATA_SUCCESS = 'FETCH_OTTEPISODE_PAGE_DATA_SUCCESS';
export const FETCH_OTTEPISODE_PAGE_DATA_FAILED = 'FETCH_OTTEPISODE_PAGE_DATA_FAILED';
