export const GET_SUGGESTIONS_LIST = 'GET_SUGGESTIONS_LIST';
export const GET_SUGGESTIONS_LIST_SUCCESS = 'GET_SUGGESTIONS_LIST_SUCCESS';
export const GET_SUGGESTIONS_LIST_FAILED = 'GET_SUGGESTIONS_LIST_FAILED';
export const CLEAR_SUGGESTIONS_LIST = 'CLEAR_SUGGESTIONS_LIST';
