export const FETCH_CHANNELS_DATA = 'FETCH_CHANNELS_DATA';
export const FETCH_CHANNELS_DATA_SUCCEEDED = 'FETCH_CHANNELS_DATA_SUCCEEDED';
export const FETCH_CHANNELS_DATA_FAILED = 'FETCH_CHANNELS_DATA_FAILED';
export const SET_SELECTED_PROGRAM = 'SET_SELECTED_PROGRAM';
export const SET_SELECTED_PROGRAM_SUCCEEDED = 'SET_SELECTED_PROGRAM_SUCCEEDED';
export const SET_SELECTED_PROGRAM_FAILED = 'SET_SELECTED_PROGRAM_FAILED';
