export const FETCH_CHANNELS_DATA = 'FETCH_CHANNELS_DATA';
export const FETCH_CHANNELS_DATA_SUCCEEDED = 'FETCH_CHANNELS_DATA_SUCCEEDED';
export const FETCH_CHANNELS_DATA_FAILED = 'FETCH_CHANNELS_DATA_FAILED';
