export const FETCH_SECTION_PAGE_DATA = 'FETCH_SECTION_PAGE_DATA';
export const FETCH_SECTION_PAGE_DATA_SUCCESS = 'FETCH_SECTION_PAGE_DATA_SUCCESS';
export const FETCH_SECTION_PAGE_DATA_FAILED = 'FETCH_SECTION_PAGE_DATA_FAILED';
